"""lets try again

Revision ID: 359f56951772
Revises: 42642f54023e
Create Date: 2023-11-16 08:41:16.768583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359f56951772'
down_revision = '42642f54023e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
